### ISSUE TITLE
Poll fn is also defined in futures_preview

### ISSUE THREAD

**Issue by PvdBerg1998** [async-rs/async-macros#5]
I see you've defined your own `poll_fn`, but also have the `futures_preview` dependency which includes a similar function. I don't know why this was done - just in case you didn't know this was the case.

**Comment by yoshuawuyts** [comment]
@PvdBerg1998 thanks for sharing; we're indeed aware. A minor-but-important difference between the two is that our `poll_fn` is an async fn, while the futures-rs version wasn't at the time we ported it.

We're fairly conservative in the structs we expose, making a deliberate effort to match stdlib. In addition to that we like being able to define our own documentation, as it makes it easier to link between implementations.

I hope this makes sense. Thanks for raising!
