### ISSUE TITLE
1.0.0 release depends on futures-preview crates

### ISSUE THREAD

**Issue by sdroege** [async-rs/async-macros#8]
I assume this should've been changed to the futures crates before release?

**Comment by yoshuawuyts** [comment]
@sdroege yeah, you're right. We got lucky here because the only macro we're currently using from this crate in `async-std` is `ready!`, which only relies on the `std::future::Future`. However I've still filed #9 to upgrade the full crate to futures 0.3.

**Comment by sdroege** [comment]
Yeah the only reason why I noticed this is because for some reason the preview crates were still in my Cargo.lock. It did not cause any problems :)

**Comment by yoshuawuyts** [comment]
published v2.0.0. Thanks!

**Comment by abonander** [comment]
@yoshuawuyts looks like you forgot to push the changes to Github. I was confused why crates was showing 2.0 that didn't seem to exist anywhere.
